"""Small reviewed metadata inventory. No AQR/French return time series copied."""

def collect(c):
    ff=[
     ('Mkt-RF','市场超额收益','market_excess_return','ff5','market_return - risk_free_return',['Mkt-RF','Rm-Rf'],'monthly',{},'Market excess return in the US factor library.'),
     ('SMB_FF3','SMB，三因子版本','smb_portfolio','ff3','(small_value + small_neutral + small_growth - big_value - big_neutral - big_growth) / 3',['SMB (FF3)','Small Minus Big (FF3)'],'annual June formation',{'sort_dimensions':['size','book_to_market']},'The FF3 size premium uses the size/value 2x3 construction.'),
     ('SMB_FF5','SMB，五因子版本','smb_portfolio','ff5','(smb_bm + smb_op + smb_inv) / 3',['SMB (FF5)','Small Minus Big (FF5)'],'annual June formation',{'sort_dimensions':['size','book_to_market','operating_profitability','investment']},'The FF5 size premium averages three component size premiums.'),
     ('HML','HML 价值多空组合','hml_portfolio','ff5','(small_value + big_value - small_growth - big_growth) / 2',['HML','High Minus Low'],'annual June formation',{},'Size-balanced value portfolio spread.'),
     ('RMW','RMW 盈利多空组合','operating_profitability','ff5','(small_robust + big_robust - small_weak - big_weak) / 2',['RMW','Robust Minus Weak'],'annual June formation',{},'Size-balanced operating-profitability portfolio spread.'),
     ('CMA','CMA 投资多空组合','investment','ff5','(small_conservative + big_conservative - small_aggressive - big_aggressive) / 2',['CMA','Conservative Minus Aggressive'],'annual June formation',{},'Size-balanced investment portfolio spread.'),
     ('Mom','Mom 动量多空组合','momentum_portfolio','ff_mom','(small_high + big_high - small_low - big_low) / 2',['Mom','French Momentum'],'monthly',{'prior_return_months':[2,12],'breakpoints':[0.3,0.7],'size_breakpoint':0.5},'Prior-return sorting excludes the most recent month.'),
     ('ST_Rev','ST_Rev 短期反转组合','short_term_reversal','ff_st','(small_low + big_low - small_high - big_high) / 2',['ST_Rev','French Short-Term Reversal'],'monthly',{'prior_return_months':[1,1]},'Previous-month return reversal portfolio.'),
     ('LT_Rev','LT_Rev 长期反转组合','long_term_reversal','ff_lt','(small_low + big_low - small_high - big_high) / 2',['LT_Rev','French Long-Term Reversal'],'monthly',{'prior_return_months':[13,60]},'Long-horizon prior-return reversal portfolio.'),
    ]
    for native,name,concept,key,formula,aliases,rebalance,params,summary in ff:
        r=c.add('french',native,name,concept,source_key=key,source_name='Kenneth French Data Library',aliases=aliases,formula=formula,raw_definition=summary,definition_kind='authored_mathematical_summary',formula_origin='independent mathematical transcription of public definition; not website prose',dialect='portfolio',quality_tier='reviewed_reference',high_quality_eligible=False,record_kind='factor_portfolio',frequency='monthly',universe='US equities: eligible NYSE/AMEX/NASDAQ; details vary by sort',rebalance=rebalance,holding_period={'value':1,'unit':'month','scope':'reported return interval; not annual formation schedule'},authors=['Eugene F. Fama','Kenneth R. French'],paper_title='A Five-Factor Asset Pricing Model' if key=='ff5' else ('Common Risk Factors in the Returns on Stocks and Bonds' if key=='ff3' else None),paper_year=2014 if key=='ff5' else (1993 if key=='ff3' else None),license='Copyright Eugene F. Fama and Kenneth R. French; no explicit open redistribution license verified',terms='Metadata and authored mathematical summaries only. No return series or website prose redistributed. Commercial data reuse unresolved.',terms_url=c.url('ff_library'),commercial_use_flag='permission_required',parameters=params,source_locator='Construction section',notes=['组合收益因子与单股票排序信号分开建模。','SMB三因子与五因子版本分开保存；未将相同简称直接合并。','论文年份保留该数据页引用的工作稿年份。'])
